version: "3"


services:
    bar:
        build: ./bar
        depends_on: 
            - mongo
        environment: 
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/BarUleam
    panel:
        build: ./panel
        depends_on: 
            - mongo
        environment: 
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/BarUleam
    autentificacion:
        build: ./autentificacion
        depends_on: 
            - mongo
        environment: 
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/BarUleam
    nginx:
        image: nginx:latest
        ports:
            - "7000:7000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - bar
            - panel
            - autentificacion
    mongo:
        image: mongo